config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "static_pages/home"
  root "static_pages#home"
  resources :subjects, only: [:index, :show] do
    resources :exams, only: [:show]
  end
  resources :users, except: :destroy
  resources :admin, only: [:index]
  resources :results, only: [:create, :new, :index]
  resources :search, only: [:index]
  namespace :admin do
    resources :users, only: [:destroy, :index]
    resources :subjects
    resources :exams
  end
  resources :responds
end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :subject
  has_many :questions, dependent: :destroy, inverse_of: :exam, autosave: true
  has_many :results

  accepts_nested_attributes_for :questions, allow_destroy: true,
    reject_if: proc {|attributes| attributes[:content].blank?}
    
  scope :search, ->(term){where "name LIKE ?", "%#{term}%"}
end

app/controllers/admin/exams_controller.rb
class Admin::ExamsController < ApplicationController
  layout "admin/application"
  before_action :verify_admin
  before_action :find_exam, except: [:index, :new, :create]
  before_action :load_subjects, except: [:index, :show, :destroy]

  def index
    @exams = Exam.all.paginate page: params[:page], per_page: 15
  end

  def show
  end

  def new
    @exam = Exam.new
    @exam.questions.build.answers.build
  end

  def create
    @exam = Exam.new exam_params
    if @exam.save
      flash[:success] = I18n.t "controller.admin.exams.successful"
      redirect_to admin_exams_path
    else
      flash[:danger] = I18n.t "controller.admin.exams.error"
      render "new"
    end
  end

  def edit
  end

  def update
    if @exam.update_attributes exam_params
      flash[:success] = I18n.t "controller.admin.exams.successful"
      redirect_to admin_exams_path
    else
      flash[:danger] = I18n.t "controller.admin.exams.error"
      render "edit"
    end
  end

  def destroy
    @exam.destroy
    flash[:success] = I18n.t "controller.admin.exams.successful"
    redirect_to admin_exams_path
  end

  private
  def exam_params
    params.require(:exam).permit(:subject_id, :name, :duration,
      questions_attributes: [:id, :content, :_destroy,
        answers_attributes: [:id, :content, :correct_answer, :_destroy]
      ]
    )
  end

  def find_exam
    @exam = Exam.find params[:id]
  end

  def load_subjects
    @subjects = Subject.all.collect {|s| [s.name, s.id]}
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController

end

app/views/admin/exams/_answer_fields.html.erb
<div class="nested-fields answer-field fieldset">
  <%= f.label :content, "Answer" %>
  <div class="row">
    <div class="col-md-11">
      <%= f.text_field :content, class: "form-control" %>
      <%= f.label :correct_answer, t(".correct"), value: "1" %>
      <%= f.check_box :correct_answer %>
      <br>
    </div>
    <div class="col-md-1">
      <%= f.hidden_field :_destroy %>
      <%= link_to "remove", "#", class: "remove_fields" %>
    </div>
</div>

app/views/admin/exams/_form.html.erb
<%= form_for [:admin , @exam] do |f| %>
  <div class="container">
    <div class="col-md-8 col-md-offset-2" >
      <div class="form-group field">
        <%= f.label :subject_id %>
        <%= f.select :subject_id, options_for_select(@subjects), {include_blank: true}, class: "form-control" %>
      </div>
      <div class="form-group field">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group field">
        <%= f.label :duration %>
        <%= f.text_field :duration, class: "form-control" %>
      </div>

      <div class="form-group field">
        <%= f.fields_for :questions do |question| %>
          <%= render "question_fields", f: question %>
        <% end %>
      </div>
      <div class="link-questions">
        <p> <%= link_to_add_fields(t("admin.exams.new.add_q"),f, :questions) %></p>
      </div>
      <div class="actions">
        <%= f.submit button, class: "btn btn-primary btn-md button" %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/exams/_question_fields.html.erb
<div class="nested-fields fieldset">
  <%= f.label :content, "Question" %><br />

  <div class="row">
    <div class="col-md-11">
      <%= f.text_area :content, rows: 3, class: "form-control" %>
      <%= f.hidden_field :_destroy %>
    </div>
    <div class="col-md-1">
      <%= link_to "remove", '#', class: "remove_fields" %>
    </div>
  </div>
  
  <div class="form-group field">
    <div class = "row">
      <%= f.fields_for :answers do |answer| %>
        <%= render "answer_fields", f: answer %>
      <% end %>
    </div>
    <%= link_to_add_fields(t("admin.exams.new.add_a"), f, :answers) %>
  </div>

</div>

app/views/admin/exams/edit.html.erb
<% provide :title, t(".title") %>
<h1><%= t(".title") %></h1>
<hr>
<%= render 'form', exam: @exam, button: t(".button") %>

app/views/admin/exams/index.html.erb
<div class="container index-exam">  
  <h1><%= t ".title" %></h1>
  <hr>
  <div class="row">
    <% @exams.each do |exam| %>
      <div class="col-md-4 box-exam">
        <%= link_to exam.name, admin_exam_path(exam)  %> 
        <p><b><%= t(".sub") %></b> <%= exam.subject.name %></p>
        <p><b><%= t(".duration") %>: </b><%= exam.duration %></p>
        <%= link_to t(".edit"), edit_admin_exam_path(exam), class: "btn btn-primary btn-md" %> 
        <%= link_to t(".delete"), admin_exam_path(exam), class: "btn btn-danger btn-md", method: :delete, data: { confirm: t(".confirm") } %> 
      </div>
    <% end %>
  </div>
  <%= will_paginate @exams %>

  <%= link_to t(".add"), new_admin_exam_path, class: "btn btn-success btn-md" %> 
</div>

app/views/admin/exams/new.html.erb
<% provide :title, t(".title") %>
<h1><%= t(".title") %></h1>
<hr>
<%= render 'form', exam: @exam, button: t(".title") %>

app/views/admin/exams/show.html.erb
<div class ="container show-exam">
  <p><strong><%= t(".name_sub") %></strong>
  <%= @exam.subject.name %></p>
  <p><strong><%= t(".name_ex") %></strong>
  <%= @exam.name %></p>
  <ul>
    <% @exam.questions.each do |q| %>
      <li><strong><%= q.content %></strong>
        <div class="option">
          <% q.answers.each do |a| %>
            <label class="container"><%= a.content %>
              <input type="radio" name="<%= q.id %>" value="<%= a.id %>" >
              <span class="checkmark"></span>
            </label>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
</div>