config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "static_pages/home"
  root "static_pages#home"
  resources :subjects, only: [:index, :show] do
    resources :exams, only: [:show]
  end
  resources :users, except: :destroy
  resources :admin, only: [:index]
  resources :results, only: [:create, :new, :index]
  resources :search, only: [:index]
  namespace :admin do
    resources :users, only: [:destroy, :index]
    resources :subjects
    resources :exams
  end
  resources :responds
end

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-inverse admin-menu">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to t(".brand"), admin_index_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to t(".home"), admin_index_path %></li>
      <li><%= link_to t(".user"), admin_users_path %></li>
      <li><%= link_to t(".subject"), admin_subjects_path %></li>
      <li><%= link_to t(".exam"), admin_exams_path %></li>
      <li><%= link_to t(".logout"), logout_path, method: :delete %></li>
    </ul>
  </div>
</nav>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
    <link href="stylesheets/style.css" rel="stylesheet" type="text/css" media="all"/>
  </head>

  <body>
  <%= render "layouts/admin/header" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
  </div>
  <%= yield %>
  </body>
</html>