config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "static_pages/home"
  root "static_pages#home"
  resources :subjects, only: [:index, :show] do
    resources :exams, only: [:show]
  end
  resources :users, except: :destroy
  resources :admin, only: [:index]
  resources :results, only: [:create, :new, :index]
  resources :search, only: [:index]
  namespace :admin do
    resources :users, only: [:destroy, :index]
    resources :subjects
    resources :exams
  end
  resources :responds
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :exams, dependent: :destroy
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < ApplicationController
  layout "admin/application"
  before_action :verify_admin
  before_action :find_subject, except: [:index, :new, :create]

  def index
    @subjects = Subject.paginate page: params[:page], per_page: 15
  end

  def show
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new subject_params
    if @subject.save
      flash[:success] = I18n.t "controller.admin.subjects.successful"
      redirect_to admin_subjects_path
    else
      flash[:danger] = I18n.t "controller.amin.subjects.error"
      render "new"
    end
  end

  def edit
  end

  def update
    if @subject.update_attributes subject_params
      flash[:success] = I18n.t "controller.admin.subjects.successful"
      redirect_to admin_subjects_path
    else
      flash[:danger] = I18n.t "controller.admin.subjects.error"
      render "edit"
    end
  end

  def destroy
    @subject.destroy
    flash[:success] = I18n.t "controller.admin.subjects.successful"
    redirect_to admin_subjects_path
  end

  private
  def find_subject
    @subject = Subject.find params[:id]
  end

  def subject_params
    params.require(:subject).permit(:name, :id)
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :find_subject, only: [:show]
  before_action :logged_in_user, only: [:index, :show]

  def index
    @subject = Subject.new
  end

  def show
  end

  private
  def find_subject
    @subject = Subject.find(subject_params[:id])
  end

  def subject_params
    params.require(:subject).permit(:name, :id)
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
  def subject_collection
    Subject.all.collect {|u| [u.name, u.id]}
  end
end

app/views/subjects/index.html.erb
<% provide :title, t(".title") %>
<div class ="user-subject">
  <%= image_tag("subject.jpg") %>
  <div class ="container">
    <div class="col-md-6 col-md-offset-3 list-choose">
      <h1><%= t(".title") %></h1>
      <%= form_for(@subject, url: subject_path(:id), method: :get) do |f| %>
        <%= f.select :id, subject_collection, {}, {class: "form-control"} %>
      <%= f.submit t(".gotest"), class: "btn btn-warning" %>
      <% end %>
      
    </div>
  </div>
</div>

app/views/subjects/show.html.erb
<div class="container">
  <h1><%= @subject.name %></h1>
  <hr>
  <div class="row">
    <% @subject.exams.each do |exam| %>
      <div class ="col-md-4 box-exam">
        <%= link_to exam.name, new_respond_path(id: exam.id), data: {confirm: t(".confirm")} %> 
        <p><b><%= t(".subject") %> :</b> <%= exam.subject.name %></p>
        <p><b><%= t(".duration") %> :</b> <%= exam.duration %></p>
      </div>
    <% end %>
  </div>
</div>